-- غیرفعال کردن RLS برای همه جداول
ALTER TABLE IF EXISTS sim_cards DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS purchase_orders DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS activation_requests DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS transactions DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS users DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS notifications DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS auction_details DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS bids DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS payment_receipts DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS support_messages DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS packages DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS commissions DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS secure_payments DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS otp_verifications DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS seller_documents DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS buyer_payment_codes DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS site_settings DISABLE ROW LEVEL SECURITY;

SELECT '✅ RLS غیرفعال شد' as result;
